"""迁移脚本

Revision ID: 51e4f3433259
Revises: 
Create Date: 2026-05-22 09:33:31.402487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51e4f3433259'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agno_sessions_created_at', table_name='agno_sessions')
    op.drop_index('idx_agno_sessions_session_type', table_name='agno_sessions')
    op.drop_table('agno_sessions')
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index('idx_agno_schema_versions_created_at', table_name='agno_schema_versions')
    op.drop_table('agno_schema_versions')
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否主键',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否查询字段',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否主键',
               existing_nullable=False)
    op.create_table('agno_schema_versions',
    sa.Column('table_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('updated_at', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('table_name'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_agno_schema_versions_created_at', 'agno_schema_versions', ['created_at'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('agno_sessions',
    sa.Column('session_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('session_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('agent_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('team_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('workflow_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('session_data', mysql.JSON(), nullable=True),
    sa.Column('agent_data', mysql.JSON(), nullable=True),
    sa.Column('team_data', mysql.JSON(), nullable=True),
    sa.Column('workflow_data', mysql.JSON(), nullable=True),
    sa.Column('metadata', mysql.JSON(), nullable=True),
    sa.Column('runs', mysql.JSON(), nullable=True),
    sa.Column('summary', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_agno_sessions_session_type', 'agno_sessions', ['session_type'], unique=False)
    op.create_index('idx_agno_sessions_created_at', 'agno_sessions', ['created_at'], unique=False)
    # ### end Alembic commands ###
